config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  # Make available necessary 'about' routes
  get 'about' => 'about#index'

  # Make available necessary 'team' routes
  get 'team' => 'team#index'

  # Make available necessary 'contact' routes
  get 'contact' => 'contact#index'
  
  # Make available necessary 'rental' routes
  get 'rentals' => 'rentals#index'
  
  # Make available necessary 'sale' routes
  get 'sales' => 'sales#index'
  
  # Make available necessary 'development' routes
  get 'developments' => 'developments#index'
  
end

app/models/broker.rb
class Broker < ActiveRecord::Base

	# Define associations and validations
	has_secure_password
	has_and_belongs_to_many :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	# Define associations and validations
	has_and_belongs_to_many :brokers

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

	# Routes to about#index
	def index
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Routes to application#index
  def index
	end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	# Routes to contact#index
	def index
	end

end

app/controllers/developments_controller.rb
class DevelopmentsController < ApplicationController

	# Routes to development#index
	def index
	end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

	# Routes to rental#index
	def index
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	# Routes to sale#index
	def index
	end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

	# Routes to team#index
	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<p style="font-size:17px">
Lorem ipsum dolor sit amet, sapien etiam, nunc amet dolor ac odio mauris justo. Luctus arcu, urna praesent at id quisque ac. Arcu massa vestibulum malesuada, integer vivamus elit eu mauris eu, cum eros quis aliquam nisl wisi.

Nulla wisi laoreet suspendisse hendrerit facilisi, mi mattis pariatur adipiscing aliquam pharetra eget. Aenean urna ipsum donec tellus tincidunt, quam curabitur metus, pretium purus facilisis enim id, integer eleifend vitae volutpat consequat per leo.

Lorem ipsum dolor sit amet, sapien etiam, nunc amet dolor ac odio mauris justo. Luctus arcu, urna praesent at id quisque ac. Arcu massa vestibulum malesuada, integer vivamus elit eu mauris eu, cum eros quis aliquam nisl wisi.
</p>

app/views/application/index.html.erb
<%= image_tag "skyline.png", {:style=>"width:950px; height:auto; max-width:100%; display:block"} %>

app/views/contact/index.html.erb
<p style="font-size:17px">
"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
<hr>
<%=form_tag	do %>

	<%= label_tag "Name" %>
	<%= text_field_tag :name, placeholder: "Required" %>
	<br>
	<br>
	<%= label_tag "Phone" %>
	<%= telephone_field :phone, placeholder: "Required" %>
	<br>
	<br>
	<%= label_tag "Email" %>
	<%= email_field :email, placeholder: "Required" %>
	<br>
	<br>
	<%= label_tag "Property ID" %>
	<%= number_field :prop_id, placeholder: "Optional" %>
	<br>
	<br>
	<%= label_tag "Message" %>
	<%= text_area_tag :message, size: "24x24", placeholder: "How can we help?" %>
	<br>
	<br>
	<%= submit_tag "Submit", :class=>"btn btn-success" %>

<% end %>

app/views/developments/index.html.erb
<p>content</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ridgeco Properties</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="main-container" class="container">
		<div class="navbar navbar-default navbar-fixed-top" style="font-size:18px; font-family:'Century Gothic',CenturyGothic,AppleGothic,sans-serif; background-color: rgba(252, 252, 252, 1)">
			<div class="container">
				<%= link_to 'RIDGECO PROPERTIES', root_path, :class => "navbar-brand", :style => "font-size:26px; color:black" %>				<button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
				</button>
				<div class="collapse navbar-collapse navHeaderCollapse">
					<ul class="nav navbar-nav navbar-right" >
						<li><%= link_to 'Rentals', rentals_path %></li>
						<li><%= link_to 'Sales', sales_path %></li>
						<li><%= link_to 'Developments', developments_path %></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="row" style="max-width: 100%; display:block; height: auto; margin-top: 120px; margin-left: 1px;">
			<div class="col-xs-1"></div>
			<div class="col-xs-10"><%= yield %></div>
			<div class="col-xs-1"></div>
		</div>

		<div class="navbar navbar-default navbar-fixed-bottom" style="font-size:18px; font-family:'Century Gothic',CenturyGothic,AppleGothic,sans-serif; background-color: rgba(252, 252, 252, 1)">
			<div class="container">
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
				</button>
				<div class="collapse navbar-collapse navHeaderCollapse">
					<ul class="nav navbar-nav" style="margin-left:436px">
						<li><%= link_to 'About', about_path, :style=>"margin-left:-90px; margin-right:90px" %></li>
						<li><%= link_to 'Team', team_path %></li>
						<li><%= link_to 'Contact', contact_path, :style=>"margin-left:90px" %></li>
					</ul>
				</div>
			</div>
		</div>

	</div>

</body>
</html>

app/views/rentals/index.html.erb
<p>content</p>

app/views/sales/index.html.erb
<p>content</p>

app/views/team/index.html.erb
<div class="row" style="max-width: 100%; display:block; height: auto;">
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
</div>

<div class="row" style="max-width: 100%; display:block; height: auto; margin-bottom:80px;">
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
	<div class="col-xs-4">
		<p style="font-size:17px; border:solid; padding:10px; margin:11px; text-align:center;">
		"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim 
		</p>
		<p style="font-size:17px; margin:11px; text-align:center; margin-bottom:50px;">Name</p>
	</div>
</div>